language: php

php:
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor

install:
  - composer install --prefer-dist

script:
  - composer run check
